var data = {
    products: [{
        "Name":"Product 1",
        "ShortDescription":"this is something we want to create just to make sure that we can earn some money with it, so let's see what happens. Good Luck!",
        "ExtendedDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer semper massa eleifend elementum sagittis. Morbi dui leo, mattis ut bibendum vel, consectetur non orci. Pellentesque mi purus, volutpat eget mollis et, scelerisque eu odio. Mauris placerat rutrum ultrices. Donec quis dapibus urna. ",
        "Price":"$xxx",
        "Discount":"true",
        "MainPicture":"img/product.jpg",
        "Picture1":"",
        "Picture2":"",
        "Picture3":"",
    },{
        "Name":"Product 1",
        "ShortDescription":"this is something we want to create just to make sure that we can earn some money with it, so let's see what happens. Good Luck!",
        "ExtendedDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer semper massa eleifend elementum sagittis. Morbi dui leo, mattis ut bibendum vel, consectetur non orci. Pellentesque mi purus, volutpat eget mollis et, scelerisque eu odio. Mauris placerat rutrum ultrices. Donec quis dapibus urna. ",
        "Price":"$xxx",
        "Discount":"false",
        "MainPicture":"img/product.jpg",
        "Picture1":"",
        "Picture2":"",
        "Picture3":"",
    },{  
        "Name":"Product 1",
        "ShortDescription":"this is something we want to create just to make sure that we can earn some money with it, so let's see what happens. Good Luck!",
        "ExtendedDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer semper massa eleifend elementum sagittis. Morbi dui leo, mattis ut bibendum vel, consectetur non orci. Pellentesque mi purus, volutpat eget mollis et, scelerisque eu odio. Mauris placerat rutrum ultrices. Donec quis dapibus urna. ",
        "Price":"$xxx",
        "Discount":"true",
        "MainPicture":"img/product.jpg",
        "Picture1":"",
        "Picture2":"",
        "Picture3":"",
    },{
        "Name":"Product 1",
        "ShortDescription":"this is something we want to create just to make sure that we can earn some money with it, so let's see what happens. Good Luck!",
        "ExtendedDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer semper massa eleifend elementum sagittis. Morbi dui leo, mattis ut bibendum vel, consectetur non orci. Pellentesque mi purus, volutpat eget mollis et, scelerisque eu odio. Mauris placerat rutrum ultrices. Donec quis dapibus urna. ",
        "Price":"$xxx",
        "Discount":"true",
        "MainPicture":"img/product.jpg",
        "Picture1":"",
        "Picture2":"",
        "Picture3":"",
    },{
        "Name":"Product 1",
        "ShortDescription":"this is something we want to create just to make sure that we can earn some money with it, so let's see what happens. Good Luck!",
        "ExtendedDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer semper massa eleifend elementum sagittis. Morbi dui leo, mattis ut bibendum vel, consectetur non orci. Pellentesque mi purus, volutpat eget mollis et, scelerisque eu odio. Mauris placerat rutrum ultrices. Donec quis dapibus urna. ",
        "Price":"$xxx",
        "Discount":"true",
        "MainPicture":"img/product.jpg",
        "Picture1":"",
        "Picture2":"",
        "Picture3":"",
    },{
        "Name":"Product 1",
        "ShortDescription":"this is something we want to create just to make sure that we can earn some money with it, so let's see what happens. Good Luck!",
        "ExtendedDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer semper massa eleifend elementum sagittis. Morbi dui leo, mattis ut bibendum vel, consectetur non orci. Pellentesque mi purus, volutpat eget mollis et, scelerisque eu odio. Mauris placerat rutrum ultrices. Donec quis dapibus urna. ",
        "Price":"$xxx",
        "Discount":"false",
        "MainPicture":"img/product.jpg",
        "Picture1":"",
        "Picture2":"",
        "Picture3":"",
    },{
        "Name":"Product 1",
        "ShortDescription":"this is something we want to create just to make sure that we can earn some money with it, so let's see what happens. Good Luck!",
        "ExtendedDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer semper massa eleifend elementum sagittis. Morbi dui leo, mattis ut bibendum vel, consectetur non orci. Pellentesque mi purus, volutpat eget mollis et, scelerisque eu odio. Mauris placerat rutrum ultrices. Donec quis dapibus urna. ",
        "Price":"$xxx",
        "Discount":"false",
        "MainPicture":"img/product.jpg",
        "Picture1":"",
        "Picture2":"",
        "Picture3":"",
    },{
        "Name":"Product 1",
        "ShortDescription":"this is something we want to create just to make sure that we can earn some money with it, so let's see what happens. Good Luck!",
        "ExtendedDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer semper massa eleifend elementum sagittis. Morbi dui leo, mattis ut bibendum vel, consectetur non orci. Pellentesque mi purus, volutpat eget mollis et, scelerisque eu odio. Mauris placerat rutrum ultrices. Donec quis dapibus urna. ",
        "Price":"$xxx",
        "Discount":"false",
        "MainPicture":"img/product.jpg",
        "Picture1":"",
        "Picture2":"",
        "Picture3":"",
    },{
        "Name":"Product 1",
        "ShortDescription":"this is something we want to create just to make sure that we can earn some money with it, so let's see what happens. Good Luck!",
        "ExtendedDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer semper massa eleifend elementum sagittis. Morbi dui leo, mattis ut bibendum vel, consectetur non orci. Pellentesque mi purus, volutpat eget mollis et, scelerisque eu odio. Mauris placerat rutrum ultrices. Donec quis dapibus urna. ",
        "Price":"$xxx",
        "Discount":"true",
        "MainPicture":"img/product.jpg",
        "Picture1":"",
        "Picture2":"",
        "Picture3":"",
    },{
        "Name":"Product 1",
        "ShortDescription":"this is something we want to create just to make sure that we can earn some money with it, so let's see what happens. Good Luck!",
        "ExtendedDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer semper massa eleifend elementum sagittis. Morbi dui leo, mattis ut bibendum vel, consectetur non orci. Pellentesque mi purus, volutpat eget mollis et, scelerisque eu odio. Mauris placerat rutrum ultrices. Donec quis dapibus urna. ",
        "Price":"$xxx",
        "Discount":"true",
        "MainPicture":"img/product.jpg",
        "Picture1":"",
        "Picture2":"",
        "Picture3":"",
    },{
        "Name":"Product 1",
        "ShortDescription":"this is something we want to create just to make sure that we can earn some money with it, so let's see what happens. Good Luck!",
        "ExtendedDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer semper massa eleifend elementum sagittis. Morbi dui leo, mattis ut bibendum vel, consectetur non orci. Pellentesque mi purus, volutpat eget mollis et, scelerisque eu odio. Mauris placerat rutrum ultrices. Donec quis dapibus urna. ",
        "Price":"$xxx",
        "Discount":"true",
        "MainPicture":"img/product.jpg",
        "Picture1":"",
        "Picture2":"",
        "Picture3":"",
    },{
        "Name":"Product 1",
        "ShortDescription":"this is something we want to create just to make sure that we can earn some money with it, so let's see what happens. Good Luck!",
        "ExtendedDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer semper massa eleifend elementum sagittis. Morbi dui leo, mattis ut bibendum vel, consectetur non orci. Pellentesque mi purus, volutpat eget mollis et, scelerisque eu odio. Mauris placerat rutrum ultrices. Donec quis dapibus urna. ",
        "Price":"$xxx",
        "Discount":"true",
        "MainPicture":"img/product.jpg",
        "Picture1":"",
        "Picture2":"",
        "Picture3":"",
    },{
        "Name":"Product 1",
        "ShortDescription":"this is something we want to create just to make sure that we can earn some money with it, so let's see what happens. Good Luck!",
        "ExtendedDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer semper massa eleifend elementum sagittis. Morbi dui leo, mattis ut bibendum vel, consectetur non orci. Pellentesque mi purus, volutpat eget mollis et, scelerisque eu odio. Mauris placerat rutrum ultrices. Donec quis dapibus urna. ",
        "Price":"$xxx",
        "Discount":"false",
        "MainPicture":"img/product.jpg",
        "Picture1":"",
        "Picture2":"",
        "Picture3":"",
    },]
}